const Pokedex = [
  {
    id: 1,
    Name: "Bulbasaur",
    Number: "#001",
    Image: "src/assets/bulbasaur.png",
    Main_Color: "#74CB48",
    Secondary_Color: "#A43E9E",
    Weigth: "6.9kg",
    Height: "0.7m",
    Main_Class: "Grass",
    Secondary_Class: "Poison",
    Main_Move: "Chlorophyll",
    Secondary_Move: "Overgrow",
    Description:
      "There is a plant seed on it´s back from the day this pokemon is born. The seed slowly grows larger",

    Stats: {
      HP: "045",
      ATK: "049",
      DEF: "049",
      SATK: "065",
      SDEF: "065",
      SPD: "045",
    },
  },

  {
    id: 2,
    Name: "Charmander",
    Number: "#004",
    Image: "src/assets/charmander.png",
    Main_Color: "#f57D31",
    Secondary_Color: "",
    Weigth: "8.5kg",
    Height: "0.6m",
    Main_Class: "Fire",
    Secondary_Class: "",
    Main_Move: "Mega-Punch",
    Secondary_Move: "Fire-Punch",
    Description:
      "It has a preference for hot things. When it rains, steam is said to spout from the tip of its tail.",

    Stats: {
      HP: "039",
      ATK: "052",
      DEF: "043",
      SATK: "080",
      SDEF: "050",
      SPD: "065",
    },
  },
  {
    id: 3,
    Name: "Squirtle",
    Number: "#007",
    Image: "src/assets/squirtle.png",
    Main_Color: "#6493EB",
    Secondary_Color: "",
    Weigth: "9kg",
    Height: "0.5m",
    Main_Class: "Water",
    Secondary_Class: "",
    Main_Move: "Torrent",
    Secondary_Move: "Rain-Dish",
    Description:
      "When it retracts its long neck into its shell, it squirts out water with vigorous force.",

    Stats: {
      HP: "044",
      ATK: "048",
      DEF: "065",
      SATK: "050",
      SDEF: "064",
      SPD: "043",
    },
  },

  {
    id: 4,
    Name: "Butterfree",
    Number: "#012",
    Image: "src/assets/butterfree.png",
    Main_Color: "#A7B723",
    Secondary_Color: "#A891EC",
    Weigth: "32kg",
    Height: "1.1m",
    Main_Class: "Bug",
    Secondary_Class: "Flying",
    Main_Move: "Compound-Eyes",
    Secondary_Move: "Tinted-Lens",
    Description:
      "In battle, it flaps its wings at great speed to release highly toxic dust into the air.",
    Stats: {
      HP: "060",
      ATK: "045",
      DEF: "050",
      SATK: "090",
      SDEF: "080",
      SPD: "070",
    },
  },

  {
    id: 5,
    Name: "Pikachu",
    Number: "#025",
    Image: "src/assets/pikachu.png",
    Main_Color: "#F9CF30",
    Secondary_Color: "",
    Weigth: "6kg",
    Height: "0.4m",
    Main_Class: "Electric",
    Secondary_Class: "",
    Main_Move: "Mega-Punch",
    Secondary_Move: "Pay-Day",
    Description:
      "Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy.",
    Stats: {
      HP: "035",
      ATK: "055",
      DEF: "040",
      SATK: "050",
      SDEF: "050",
      SPD: "090",
    },
  },

  {
    id: 6,
    Name: "Gastly",
    Number: "#092",
    Image: "src/assets/gastly.png",
    Main_Color: "#70559B",
    Secondary_Color: "#A43E93",
    Weigth: "0.1kg",
    Height: "1.3m",
    Main_Class: "Ghost",
    Secondary_Class: "Poison",
    Main_Move: "Levitate",
    Secondary_Move: "",
    Description:
      "Born from gases, anyone would faint if engulfed by its gaseous body, which contains poison.",
    Stats: {
      HP: "030",
      ATK: "035",
      DEF: "030",
      SATK: "100",
      SDEF: "035",
      SPD: "080",
    },
  },

  {
    id: 7,
    Name: "Ditto",
    Number: "#132",
    Image: "src/assets/ditto.png",
    Main_Color: "#AAA67F",
    Secondary_Color: "",
    Weigth: "4.0kg",
    Height: "0.3m",
    Main_Class: "Normal",
    Secondary_Class: "",
    Main_Move: "Limber",
    Secondary_Move: "Imposter",
    Description:
      "It can reconstitute its entire cellular structure to change into what it sees, but it returns to normal when it relaxes.",
    Stats: {
      HP: "048",
      ATK: "048",
      DEF: "048",
      SATK: "048",
      SDEF: "048",
      SPD: "048",
    },
  },

  {
    id: 8,
    Name: "Mew",
    Number: "#152",
    Image: "src/assets/mew.png",
    Main_Color: "#FB5584",
    Secondary_Color: "",
    Weigth: "4.0kg",
    Height: "0.4m",
    Main_Class: "Psychic",
    Secondary_Class: "",
    Main_Move: "Synchronize",
    Secondary_Move: "",
    Description:
      "When viewed through a microscope, this Pokémon’s short, fine, delicate hair can be seen.",
    Stats: {
      HP: "100",
      ATK: "100",
      DEF: "100",
      SATK: "100",
      SDEF: "100",
      SPD: "100",
    },
  },
  {
    id: 9,
    Name: "Aron",
    Number: "#304",
    Image: "src/assets/aron.png",
    Main_Color: "#B7B9D0",
    Secondary_Color: "#B69E31",
    Weigth: "60kg",
    Height: "0.4m",
    Main_Class: "Steel",
    Secondary_Class: "Rock",
    Main_Move: "Sturdy",
    Secondary_Move: "Rock-Head",
    Description:
      "It eats iron ore - and sometimes railroad tracks - to build up the steel armor that protects its body.",

    Stats: {
      HP: "050",
      ATK: "070",
      DEF: "100",
      SATK: "040",
      SDEF: "040",
      SPD: "030",
    },
  },
];

export default Pokedex;
